### ISSUE TITLE
Add types for token

### ISSUE THREAD

**Issue by hawyar** [spotify-api/spotify-types#1]
I would like to have types for the token object returned from the access token request.
```ts
interface Token {
  accessToken: string;
  tokenType: string;
  expiresIn: number;
}
```
I can open a PR for it. Thank you

**Comment by scientific-dev** [comment]
Yeah if you are willing to create a PR, then you can proceed.

**Comment by scientific-dev** [comment]
Thanks for your contribution!
The changes will be updated soon!

**Comment by scientific-dev** [comment]
Sorry for a very late response! 

The changes you made in #2 has been update in [v1.0.5](https://github.com/spotify-api/spotify-types/releases/tag/1.0.5).
