### ISSUE TITLE
Missing types for the `recently-played` endpoint

### ISSUE THREAD

**Issue by rocktimsaikia** [spotify-api/spotify-types#4]
I could not find any typings for the `recently-played` endpoint.
https://developer.spotify.com/console/get-recently-played/

**Comment by scientific-dev** [comment]
Sorry for a really late response. When I was initially developing the package, i too was not able to find typings so i did multiple requests with various methods and created typings for it based on it.

You can close this issue if you don't have any further questions.

**Comment by rocktimsaikia** [comment]
I was hoping those typings could be added to this lib?

**Comment by scientific-dev** [comment]
> I was hoping those typings could be added to this lib?

Well, it already does exist as [RecentlyPlayed] in the library.
Documentation: https://spotify-api.js.org/main/interface/RecentlyPlayed

You can close this issue if you are satisfied that the issue has been resolved.

**Comment by rocktimsaikia** [comment]
Yes. But I am not using that lib actually. I only needed the typings that's why I was using this typing lib assuming all the typing would be available here. But I guess this lib only offers the typings that `spotify-api.js` is missing.

**Comment by scientific-dev** [comment]
Ok, now i understand. Sorry, for not understanding your issue earlier. 

I have added the [RecentlyPlayed] interface in [v1.0.7](https://github.com/spotify-api/spotify-types/releases/tag/1.0.7). It will be soon updated in the documentation. 
I guess with this your issue has been resolved.
